### ISSUE TITLE
Dreamcast Arcade Stick, unmapped Z button.

### ISSUE THREAD

**Issue by GamaMak** [SonicFreak94/triolinker-vjoy#11]
Hey thanks for your work!
Both the vjoy and the new xinput version work ok with the Dreamcast Arcade Stick, except the Z button.
![image](https://user-images.githubusercontent.com/22858397/58322934-202ca100-7e2b-11e9-85aa-ee84936fb332.png)

**Comment by michael-fadely** [comment]
The button appears to be defined and configured here [here](https://github.com/michael-fadely/triolinker-vjoy/blob/master/triolinker-vjoy/main.cpp#L49) and [here](https://github.com/michael-fadely/triolinker-vjoy/blob/master/triolinker-vjoy/main.cpp#L138) respectively. The issue could either be that the device isn't reporting the button, or that the bitmask is incorrectly defined.

I don't actually have access to the adapter in question, but later on today I can develop a command line option that will show the raw data from the HID reports, and then you will be able to run it and see first hand if the Z button is being reported.

Thanks for the report!

**Comment by GamaMak** [comment]
That's great!

All i can say until i run your command line option, is that i can see that the Z button works in https://html5gamepad.com/ and joytester.exe.

Thank you so much, for the swift response!

**Comment by GamaMak** [comment]
By the way, using your tool from the:
**"Trying with Gamecube controller, but Z and yellow joystick not responding"** thread, i can see:

Second column:
A=04
B=02
X=08
Y=01
C=80
**Z=40**

Third column
START=02

I don't know, but hope that helps.

**Comment by michael-fadely** [comment]
I believe #12 has fixed this issue. Could you test out this build and let me know?
https://ci.appveyor.com/project/SonicFreak94/triolinker-vjoy/build/job/txxd23q9bci4v5fg/artifacts

**Comment by GamaMak** [comment]
Ok, i tried the vjoy-x360ce depended  
https://ci.appveyor.com/api/buildjobs/dq4gyht4xya4kgq7/artifacts/x64%2FRelease%20x64.zip
and it is working perfect!

I have to say, that building a tool, useful to so few people,  but so valuable, is simply amazing.

Thanks, you made my day :)

No sleep tonight, Dragon Ball FighterZ till sunrise hahaha.

**Comment by michael-fadely** [comment]
My pleasure! Anything to keep Dreamcast hardware going strong.
