### ISSUE TITLE
Axis problem with Cobalt Flux dance mat

### ISSUE THREAD

**Issue by scripter81** [SonicFreak94/triolinker-vjoy#8]
Hello, I managed to let my Trio Linker work again with Win 7 64bit, but I'm experiencing the axis problem while using my cobalt flux dance mat with stepmania.

The issue is that if you press both up/bottom or left/right buttons together, they are not recognized from stepmania, nor from the vJoy monitor, in fact the POV's indicator return to middle while I press both the triggers.

Maybe it's something I can fix in the settings?

Thanks in advance

**Comment by PiKeyAr** [comment]
Try setting UnlinkDPad to false in the config file.

**Comment by scripter81** [comment]
Thank you so much for the quick response.

I checked both the folder of the compiled version and the source code, but I can't find any config.ini file. Do I have to create it?

**Comment by PiKeyAr** [comment]
This was the last build before I stopped working on it, config.ini is included: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/TrioLinker/25dec.zip

**Comment by scripter81** [comment]
Hi PiKeyAr,
I edited the config.ini and runned the feeder, the trio is detected, but the vjoy monitor return the POV to the middle while I click both up/down left/right.
Also Stepmania do not recognize it :<

Let me know if I can try something else.

Thank you again

**Comment by PiKeyAr** [comment]
It could be that the dance mat uses other axes that aren't currently recognized by the feeder. If you could make a report similar to issue #4 (particularly [this](https://github.com/SonicFreak94/triolinker-vjoy/issues/4#issuecomment-353761366) post and the one after it), I could try to add those axes in the feeder.

If the test program doesn't show any input from those axes, then unfortunately I can't help you.

**Comment by scripter81** [comment]
Hi PiKeyAr,
the program detect the device. Here the output.
I 'm not posting the diagnostic starting data cause it's exactly the same ZaphodJustSomeGuy posted in the issue #4 .

I'm not going to post up+left up+right down+left down+right, cause are currently working, but if you need it just tell me.

Thank you very much for the help.

The intial 7 couple are:
00 00 00 80 80 80 80

Pressing right:
00 00 20 FF 80 FF 80
Pressing left:
00 00 80 00 80 00 80
Pressing left+right
00 00 A0 00 80 00 80

Pressing up:
00 00 10 80 00 80 00
Pressing down:
00 00 40 80 FF 80 FF
Pressing up+down
00 00 50 80 FF 80 FF

**Comment by PiKeyAr** [comment]
OK, I see why this is happening.

The feeder uses the input from the third field to simulate a D-Pad, which is a 360-degree POV. I don't think it's possible to simulate a POV where you could press both up and down simultaneously because that would be 0/0, which equals to not pressing anything.

However, one workaround for this would be treating the field's input as separate buttons. I've pushed a change to my fork over here: https://github.com/PiKeyAr/triolinker-vjoy that adds buttons 9, 10, 11 and 12 for Up, Down, Left and Right.

Unfortunately I don't have the SDK installed at the moment and it will take a while to download because of traffic limits with my ISP, so you'll have to either compile this version yourself or ask someone else to compile it for you. Once you have the compiled executable, add the following line to config.ini:
`DPadAsButtons=true`

This should be enough to get simultaneous inputs registered in the feeder.

**Comment by scripter81** [comment]
Hi PiKeyAr,
I'm a web programmer, so I'm not used to compile things, but at least I know what are we talking about.
 
I'll try using visual studio community and let you know asap.

Thank you a lot, and have a nice day

**Comment by scripter81** [comment]
Hi PiKeyAr,
I managed to compile the exe, I had to change few parameters regarding some deprecated function, and also the SDK version.
I created the exe file but when I launch it I recive a "USB device not found" message.

Maybe I compiled it in a wrong way, I don't know :disappointed: 

In vJoy I set 13 button (I wasn't sure if it's zero-based or what).

**Comment by PiKeyAr** [comment]
Try compiling under the v141_xp toolset. The code should compile as-is, you might need the driver SDK though. Like I said, my Internet connection is very slow at the moment so I won't be able to help for a while.

**Comment by PiKeyAr** [comment]
Use this build: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/TrioLinker/23mar-dpadasbuttons.zip
Using my Dreamcast controller I was able to confirm that it detects the D-Pad as individual buttons now. Your vJoy device must have 12 buttons in its settings.

**Comment by scripter81** [comment]
Hi PiKeyAr,
I tested it with the vJoy monitor but also within Stepmania and it's working!!
You saved my Cobalt Flux from years of dust, I can finally use it on 64bit systems.

Thank you so much, and have a nice day!

PS I think we can close this issue
